name: SW GUILD APP GITHUB CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events
  push:
<<<<<<< HEAD
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
=======
    branches: 
      - '**'
  pull_request:
    branches: 
      - '**'
>>>>>>> 22806a4... Create github_ci.yml

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build & Test
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
<<<<<<< HEAD

=======
    
>>>>>>> 22806a4... Create github_ci.yml
    strategy:
      matrix:
        node-version: [12.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
<<<<<<< HEAD

=======
            
>>>>>>> 22806a4... Create github_ci.yml
      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm ci
<<<<<<< HEAD

=======
          
>>>>>>> 22806a4... Create github_ci.yml
      - name: Run Unit Tests
        run: npm run ci:test

      - name: Clean Distribution Directory
        run: npm run ci:clean
<<<<<<< HEAD

      - name: Build Application
        run: npm run ci:build

=======
        
      - name: Build Application
        run: npm run ci:build
      
>>>>>>> 22806a4... Create github_ci.yml
      - name: List Files in Distribution Directory
        run: ls -R ./dist
